---
title: "Sweep"
author: "Wal McConnell"
date: "26 October 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sweep)
library(forecast)
library(tidyquant)
library(timetk)  
```

http://www.business-science.io/code-tools/2017/10/25/demo_week_sweep.html


# Data

Data taken from https://fred.stlouisfed.org/series/S4248SM144NCEN

```{r}
beer_sales_tbl <- tq_get("S4248SM144NCEN", 
                         get = "economic.data", 
                         from = "2010-01-01", 
                         to = "2016-12-31")

beer_sales_tbl
```

```{r}
beer_sales_tbl %>%
    ggplot(aes(date, price)) +
    geom_line(col = palette_light()[1]) +
    geom_point(col = palette_light()[1]) +
    geom_ma(ma_fun = SMA, n = 12, size = 1) +
    theme_tq() +
    scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
    labs(title = "Beer Sales: 2007 through 2016")
```

# Forecast & Sweep


## Step 1 : TS Object
```{r}
# Convert from tbl to ts
beer_sales_ts <- tk_ts(beer_sales_tbl, start = 2010, freq = 12)

beer_sales_ts

# Check that ts-object has a timetk index
has_timetk_idx(beer_sales_ts)

```

# Step 2 : Model using ARIMA

```{r}
fit_arima <- auto.arima(beer_sales_ts)

fit_arima

# sw_tidy - Get model coefficients
sw_tidy(fit_arima)

# sw_glance - Get model description and training set accuracy measures
sw_glance(fit_arima) %>% glimpse()

# sw_augment - get model residuals
sw_augment(fit_arima, timetk_idx = TRUE)

# Plotting residuals
sw_augment(fit_arima, timetk_idx = TRUE) %>%
    ggplot(aes(x = index, y = .resid)) +
    geom_point() + 
    geom_hline(yintercept = 0, color = "red") + 
    labs(title = "Residual diagnostic") +
    scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
    theme_tq()


```

# Step 3 : Forecast

```{r}
fcast_arima <- forecast(fit_arima, h = 12)
fcast_arima
```

# Step 4 - Tidy the forecast

```{r}
has_timetk_idx(fcast_arima)

fcast_tbl <- sw_sweep(fcast_arima, timetk_idx = TRUE)

fcast_tbl

```


# Step 5 - Compare Forecast


```{r}
actuals_tbl <- tq_get("S4248SM144NCEN", 
                      get = "economic.data", 
                      from = "2017-01-01", 
                      to = "2017-12-31")

fcast_tbl %>%
    ggplot(aes(x = index, y = price, color = key)) +
    # 95% CI
    geom_ribbon(aes(ymin = lo.95, ymax = hi.95), 
                fill = "#D5DBFF", color = NA, size = 0) +
    # 80% CI
    geom_ribbon(aes(ymin = lo.80, ymax = hi.80, fill = key), 
                fill = "#596DD5", color = NA, size = 0, alpha = 0.8) +
    # Prediction
    geom_line() +
    geom_point() +
    # Actuals
    geom_line(aes(x = date, y = price), color = palette_light()[[1]], data = actuals_tbl) +
    geom_point(aes(x = date, y = price), color = palette_light()[[1]], data = actuals_tbl) +
    # Aesthetics
    labs(title = "Beer Sales Forecast: ARIMA", x = "", y = "Thousands of Tons",
         subtitle = "sw_sweep tidies the auto.arima() forecast output") +
    scale_x_date(date_breaks = "1 year", date_labels = "%Y") +
    scale_color_tq() +
    scale_fill_tq() +
    theme_tq()
```

Investigate the error

```{r}
# Investigate test error 
error_tbl <- left_join(actuals_tbl, fcast_tbl, by = c("date" = "index")) %>%
    rename(actual = price.x, pred = price.y) %>%
    select(date, actual, pred) %>%
    mutate(
        error     = actual - pred,
        error_pct = error / actual
        ) 
error_tbl

# Calculate test error metrics
test_residuals <- error_tbl$error
test_error_pct <- error_tbl$error_pct * 100 # Percentage error

me   <- mean(test_residuals, na.rm=TRUE)
rmse <- mean(test_residuals^2, na.rm=TRUE)^0.5
mae  <- mean(abs(test_residuals), na.rm=TRUE)
mape <- mean(abs(test_error_pct), na.rm=TRUE)
mpe  <- mean(test_error_pct, na.rm=TRUE)

tibble(me, rmse, mae, mape, mpe) %>% glimpse()
```

